
namespace NodeJS {
  interface ProcessEnv {
    PGUSER: string;
    PGHOST: string;
    PGDATABASE: string;
    PGPASSWORD: string;
    PGPORT: string;
  }
}
// This file is automatically generated.
// It should not be edited manually.
// This will remove TS warnings about undefined env vars.