import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/context/CartContext";
import CartIcon from "@/components/CartIcon";
import Link from "next/link";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ordering System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastContainer 
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <CartProvider>
          <header className="bg-[#3a0ca3] text-white shadow-sm py-4 px-6">
            <div className="max-w-6xl mx-auto flex justify-between items-center">
              <h1 className="text-xl font-bold">Ordering System</h1>
              <div className="flex items-center space-x-4">
                <Link href="/" className="px-3 py-1 border border-white rounded-md hover:bg-white hover:text-[#3a0ca3] transition-colors">
                  Home
                </Link>
                <Link href="/admin" className="px-3 py-1 border border-white rounded-md hover:bg-white hover:text-[#3a0ca3] transition-colors">
                  Admin
                </Link> {/* will be redirect upon logging in */}
                <Link href="/menu" className="px-3 py-1 border border-white rounded-md hover:bg-white hover:text-[#3a0ca3] transition-colors">
                  Menu
                </Link>
                <CartIcon />
              </div>
            </div>
          </header>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}